<a href="https://colab.research.google.com/github/neto-riga/Metodos_Numericos/blob/main/Ejercicio_8_M%C3%A9todo_de_Intercambio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Método de intercambio
#### Martínez Venegas Raúl
#### Rivera Gálvez Ernesto
---

Obtener la inversa de la siguiente matriz por el método de intercambio. 
$$
\begin{bmatrix}
4 &3  &-2 &1 \\
1 &-3 &0  &-1 \\
2 &1  &3  &-2 \\
2 &-2 &3  &-3
\end{bmatrix}
$$


In [ ]:
import numpy as np
from sympy import Matrix, init_printing
init_printing()

Para comenzar, inicializamos nuestra matriz y colocamos un par de listas que nos ayudaran a saber sobre que $x_{n}$ y $b_{n}$ hemos trabajado y más adelante ordenaremos.

In [ ]:
A = np.zeros((4,4))
A[0] = [4, 3, -2, 1]
A[1] = [1, -3, 0, -1]
A[2] = [2, 1, 3, -2]
A[3] = [2, -2, 3, -3]
fila = []
columna = []

Tenemos una matriz de $n \times n$, por lo tanto, realizaremos el proceso del método de intercambio $n - 1$ veces para después poder identificar cual eson las últimas $x_{n}$ y $b_{n}$ que debemos intercambiar. 

In [ ]:
for iter in range(len(A) - 1):
  mayor = 0
  for fila_ in A:
    for elemento in fila_:
      if abs(mayor) < abs(elemento): 
        mayor = elemento
  loc = np.where(A == mayor)
  fila.append(loc[0][0])
  columna.append(loc[1][0])

  for i in range(len(A)):
    if i != columna[iter]: A[fila[iter], i] = A[fila[iter], i] / (- mayor)

  for i in range(len(A)):
    k = A[i, columna[iter]]
    for j in range(len(A)):
      if j != columna[iter] and i != fila[iter]:
        A[i,j] += k * A[fila[iter], j]

  for i in range(len(A)):
    if i == fila[iter]:
      A[i, columna[iter]] = 1 / mayor
    else:
      A[i, columna[iter]] /= mayor
  print(f"Iteracion {iter+1}, pivote: {mayor :.3f}\n{A}\n")

Iteracion 1, pivote: 4.000
[[ 0.25 -0.75  0.5  -0.25]
 [ 0.25 -3.75  0.5  -1.25]
 [ 0.5  -0.5   4.   -2.5 ]
 [ 0.5  -3.5   4.   -3.5 ]]

Iteracion 2, pivote: 4.000
[[ 0.1875 -0.6875  0.125   0.0625]
 [ 0.1875 -3.6875  0.125  -0.9375]
 [-0.125   0.125   0.25    0.625 ]
 [ 0.     -3.      1.     -1.    ]]

Iteracion 3, pivote: -3.688
[[ 0.15254237  0.18644068  0.10169492  0.23728814]
 [ 0.05084746 -0.27118644  0.03389831 -0.25423729]
 [-0.11864407 -0.03389831  0.25423729  0.59322034]
 [-0.15254237  0.81355932  0.89830508 -0.23728814]]



Una vez hemos realizado el proceso $n - 1$ veces (en este caso tres veces), identificamos la fila y columna que no hemos cambiado y realizamos el método en dicha $x_{n}$ y $b_{n}$ como pivote sin importar si es el mayor o no. 

In [ ]:
for i in range(len(A)):
  for j in range(len(A)):
    if i not in fila and j not in columna:
      mayor = A[i,j]

iter +=1

loc = np.where(A == mayor)
fila.append(loc[0][0])
columna.append(loc[1][0])

for i in range(len(A)):
  if i != columna[iter]:
    A[fila[iter], i] = A[fila[iter], i] / (- mayor)

for i in range(len(A)):
  k = A[i, columna[iter]]
  for j in range(len(A)):
    if j != columna[iter] and i != fila[iter]:
      A[i,j] += k * A[fila[iter], j]

for i in range(len(A)):
  if i == fila[iter]:
    A[i, columna[iter]] = 1 / mayor
  else:
    A[i, columna[iter]] /= mayor

T = Matrix(A)
T.evalf(5)

⎡   0        1.0      1.0      -1.0  ⎤
⎢                                    ⎥
⎢0.21429   -1.1429  -0.92857  1.0714 ⎥
⎢                                    ⎥
⎢  -0.5      2.0      2.5      -2.5  ⎥
⎢                                    ⎥
⎣-0.64286  3.4286    3.7857   -4.2143⎦

Finalmente, cambiamos el orden de las filas y columnas al orden inicial.

In [ ]:
for i in range(len(A)):
  cambio = fila.index(i)
  A[[i, cambio]] = A[[cambio, i]]
  A[:, [i, cambio]] = A[:, [cambio, i]]

print("Matriz inverza")
T = Matrix (A)
T.evalf(5)

Matriz inverza


⎡   0        1.0      1.0      -1.0  ⎤
⎢                                    ⎥
⎢0.21429   -1.1429  -0.92857  1.0714 ⎥
⎢                                    ⎥
⎢  -0.5      2.0      2.5      -2.5  ⎥
⎢                                    ⎥
⎣-0.64286  3.4286    3.7857   -4.2143⎦